# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: chrysaliswoon
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: helloworld-severless
# "service" is the name of this project. This will also be added to your AWS resource names.
service: chrysalis-serverless
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline